; --- MATRIX_ERROR_INVALID_REGISTER ---
    MOV     A0, MAT[r1][rn]        ; 'rn' is invalid

; --- MATRIX_ERROR_LABEL_TOO_LONG ---
MO1: MOV     A0, THIS_LABEL_IS_WAY_TOO_LONG_FOR_THE_LIMIT[r1][r2]

; --- MATRIX_ERROR_EMPTY_INDEX ---
MO2: MOV     A0, MAT[][r2]

; --- MATRIX_ERROR_INVALID_REGISTER (bad name) ---
MO3: MOV     A0, MAT[x1][r2]

; --- MATRIX_ERROR_NON_REGISTER ---
MO4: MOV     A0, MAT[5][r2]

; --- MATRIX_ERROR_JUNK_BETWEEN_BRACKETS ---
MO5: MOV     A0, MAT[r1 + r2][r3]

; --- MATRIX_ERROR_MISSING_CLOSE_BRACKET ---
MO6: MOV     A0, MAT[r1][r2

; --- MATRIX_ERROR_MISSING_SECOND_OPEN ---
MO7: MOV     A0, MAT[r1]r2]

; --- MATRIX_ERROR_MISSING_SECOND_CLOSE ---
MO8: MOV     A0, MAT[r1][r2
